version: "3.9"

services:
  web:
    build:
      context: ./docker
      dockerfile: Dockerfile
    environment:
      PHP_IDE_CONFIG: "serverName=${PHP_IDE_CONFIG:-localhost}"
    volumes:
      - .:/var/www/html
      - ./docker/src/apache2/conf.d/web.conf:/etc/apache2/conf.d/web.conf
      - ./docker/src/php/xdebug.ini:/etc/php7/conf.d/xdebug.ini
      - ./docker/src/php/php.ini:/usr/local/etc/php/php.ini
    ports:
      - ${DOCKER_APP_PORT:-80}:80
    networks:
      - unotifi
    depends_on:
      - db

  db:
    image: mysql:5.6
    environment:
      MYSQL_USER: "${MYSQL_USER:?err}"
      MYSQL_PASSWORD: "${MYSQL_USER_PASSWORD:?err}"
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD:?err}"
      MYSQL_DATABASE: "${MYSQL_DATABASE:?err}"
    volumes:
      - ./docker/src/db/:/docker-entrypoint-initdb.d
      - mysql-data:/var/lib/mysql
    ports:
      - ${DOCKER_MYSQL_PORT:-3306}:3306
    networks:
      - unotifi

  db-test:
    image: mysql:5.6
    environment:
      MYSQL_USER: "${MYSQL_USER:?err}"
      MYSQL_PASSWORD: "${MYSQL_USER_PASSWORD:?err}"
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD:?err}"
      MYSQL_DATABASE: "unotifi_com_dealership_test"
    volumes:
      - ./docker/src/db/:/docker-entrypoint-initdb.d
      - mysql-data-test:/var/lib/mysql
    ports:
      - ${DOCKER_MYSQL_TEST_PORT:-3307}:3306
    networks:
      - unotifi

networks:
  unotifi:

volumes:
  mysql-data:
  mysql-data-test:
