version: "3.9"

services:
  web:
    build:
      context: ./docker
      dockerfile: Dockerfile
    environment:
      PHP_IDE_CONFIG: "serverName=${PHP_IDE_CONFIG:-localhost}"
    volumes:
      - .:/var/www/html
      - ./docker/src/apache2/conf.d/web.conf:/etc/apache2/conf.d/web.conf
      - ./docker/src/php/xdebug.ini:/etc/php7/conf.d/xdebug.ini
      - ./docker/src/php/php.ini:/usr/local/etc/php/php.ini
    ports:
      - ${DOCKER_APP_PORT:-80}:80
    networks:
      - emagia


networks:
  emagia:
